//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRF_beadando
{
    using System;
    using System.Collections.Generic;
    
    public partial class Esemeny
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Esemeny()
        {
            this.Budapest_10km = new HashSet<Budapest_10km>();
            this.Mikulas_futas = new HashSet<Mikulas_futas>();
            this.Nyar_koszonto_futas = new HashSet<Nyar_koszonto_futas>();
        }
    
        public string ESEMENY_ID { get; set; }
        public string NEV { get; set; }
        public System.DateTime DATUM { get; set; }
        public string HELYSZIN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Budapest_10km> Budapest_10km { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mikulas_futas> Mikulas_futas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nyar_koszonto_futas> Nyar_koszonto_futas { get; set; }
    }
}
