//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRF_beadando
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities : DbContext
    {
        public Database1Entities()
            : base("name=Database1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Budapest_10km> Budapest_10km { get; set; }
        public virtual DbSet<Esemeny> Esemenies { get; set; }
        public virtual DbSet<Felhasznalo> Felhasznaloes { get; set; }
        public virtual DbSet<Idomero> Idomeroes { get; set; }
        public virtual DbSet<Mikulas_futas> Mikulas_futas { get; set; }
        public virtual DbSet<Nyar_koszonto_futas> Nyar_koszonto_futas { get; set; }
    }
}
