//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRF_beadando
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities4 : DbContext
    {
        public Database1Entities4()
            : base("name=Database1Entities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Budapest_10km> Budapest_10km { get; set; }
        public virtual DbSet<Esemeny> Esemeny { get; set; }
        public virtual DbSet<Felhasznalo> Felhasznalo { get; set; }
        public virtual DbSet<Idomero> Idomero { get; set; }
        public virtual DbSet<Mikulas_futas> Mikulas_futas { get; set; }
        public virtual DbSet<Nyar_koszonto_futas> Nyar_koszonto_futas { get; set; }
    }
}
